### ISSUE TITLE
tạm ẩn năng lực cung [0.1d]

### ISSUE THREAD

**Issue by SuTran** [FoodMapAsia/efarm-admin#12]
![image](https://user-images.githubusercontent.com/4506521/187393768-d40c89ad-87d3-4e6b-8812-a78b45fefa99.png)

**Comment by qunahui** [comment]
issue này bên app đúng không a ? Mình cũng sẽ ẩn bên web admin luôn a nhỉ ?

**Comment by SuTran** [comment]
ừa, update 2 bên luôn e nhé
