### ISSUE TITLE
Nhà cung summary

### ISSUE THREAD

**Issue by SuTran** [FoodMapAsia/efarm-admin#6]
Tổng diện tích
Tổng số farm
Tổng sản lượng

**Comment by qunahui** [comment]
Hiện tại diện tích mình chỉ có một field thể hiện. Còn tổng số farm nghĩa là như thế nào a nhỉ ?

**Comment by SuTran** [comment]
tổng số farm là tổng số nhà cung thuộc loại "Hộ gia đình" e nhé
