### ISSUE TITLE
tuỳ chọn vựa , sản phẩm chung, thiếu giấy phép kinh doanh [0.5d]

### ISSUE THREAD

**Issue by SuTran** [FoodMapAsia/efarm-admin#7]
<img width="976" alt="image" src="https://user-images.githubusercontent.com/4506521/187389611-b957c5ba-d504-42aa-ae8f-91f1b6fa874a.png">

**Comment by qunahui** [comment]
Anh có thể nói cụ thể ý "tùy chọn vựa" được không ạ ?

**Comment by SuTran** [comment]
ý là vựa thì k cần chọn cũng được em. ví dụ role producer builder thì họ cũng k thuộc 1 vựa nào cả

**Comment by qunahui** [comment]
> ý là vựa thì k cần chọn cũng được em. ví dụ role producer builder thì họ cũng k thuộc 1 vựa nào cả

Input vựa ở đây sẽ bắt buộc vì nó dùng để query các producer theo account tạo, nếu không sử dụng input vựa thì phải dùng 1 cách khác là creatorId, mà làm vậy thì sẽ cần chỉnh lại database query hết theo creatorId đó a.

**Comment by SuTran** [comment]
a thấy e nên design api theo role, nên là 2 api khác nhau
- nếu role là vựa => list producer theo vựa 
- nếu role là producerMapBuilder => list producer theo creatorID
