### ISSUE TITLE
CRUD danh mục tổng (Trái cây, Trà, Cà Phê)

### ISSUE THREAD

**Issue by SuTran** [FoodMapAsia/efarm-admin#9]

**Comment by qunahui** [comment]
Vậy giờ mình sẽ tách ra làm 2 loại là danh mục sản phẩm và danh mục cho các sổ tay a @SuTran nhỉ ?

**Comment by SuTran** [comment]
danh mục theo cây được k e nhỉ?

ví dụ:
Trái cây
|-- Bơ
|-- Ổi
Trà
|--...
|--...

**Comment by qunahui** [comment]
> danh mục theo cây được k e nhỉ?
> 
> ví dụ: Trái cây |-- Bơ |-- Ổi Trà |--... |--...

Hiện tại thì thiết kế dưới db có hỗ trợ dạng cây như thế này nha anh @SuTran. Ý em muốn hỏi là hiện tại mình có cần tách danh mục riêng cho sản phẩm và sổ tay chưa anh nhỉ ?

**Comment by SuTran** [comment]
sẽ xài chung danh mục nhé
